### PR TITLE
Add compatibilty to eZ Platform 3

### PR DESCRIPTION
**Pull request by jbcr**
The new version of Ez Platform 3 adds many [backward compatibilities](https://doc.ezplatform.com/en/master/releases/ez_platform_v3.0_deprecations/).

This PR adds:
* Compatibility to eZ Platrform 3.0
* Backward compatibility to eZ Platform 2.5

### CODE REVIEW

**Comment by pboethig** [comment]
whats the state of this issue?

**Comment by jbcr** [comment]
> whats the state of this issue?

Hi @pboethig,

Thanks for your interest. This PR is always in "work in progress".

Any help is welcome ;-)

To contribute, fork this repository and make a pull request with `plateform3` on the targeted branch.

I can't wait to read you.

**Comment by pboethig** [comment]
hi,

why is it in progress sice nov 2019?

one year is a long time

whats the problem?

Peter

Am Fr., 4. Sept. 2020 um 08:46 Uhr schrieb jbcr <notifications@github.com>:

**Comment by jbcr** [comment]
Hi,

The development of the new version for eZ Platform 3 is not technically locked.

This PR has received a new contribution. Can you test it and report your experience?

You need to use the `dev-platform3` version for eZ Dataflow Bundle and use the `dev-master` for the [DataflowBundle](https://github.com/code-rhapsodie/dataflow-bundle).

Thank you,

**Comment by jbcr** [comment]
Hi @pboethig ,

The development of the new version for eZ Platform 3 is not technically locked.

This PR has received a new contribution. Can you test it and report your experience?

You need to use the `dev-platform3` version for eZ Dataflow Bundle and use the `dev-master` for the [DataflowBundle](https://github.com/code-rhapsodie/dataflow-bundle).

Thank you,

**Review by jeremycr — APPROVED** [review]
Good job!

**Comment by jbcr** [comment]
@pboethig The new version 3.0 of eZDataflowBundle is now available for Ibexa content 3.

**Pull request merged**
